[tox]
envlist = py310,py311,py312,py313
isolated_build = True

[testenv]
allowlist_externals = uv
setenv = DJANGO_SETTINGS_MODULE=tests.settings
commands =
    uv sync
    uv run pytest

[testenv:hooks]
deps = prek
commands = prek run --all-files

[testenv:pre-commit]
deps = {[testenv:hooks]deps}
commands = {[testenv:hooks]commands}
