# Generated by Django 4.1.4 on 2023-01-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indieweb", "0003_auto_20190518_0207"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auth",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="token",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
