# Generated by Django 5.2.2 on 2025-06-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indieweb", "0004_alter_auth_id_alter_token_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auth",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="auth",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="token",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="token",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
