# Generated by Django 5.2.3 on 2025-06-28 20:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("indieweb", "0002_alter_auth_state"),
        ("indieweb", "0005_alter_auth_created_alter_auth_modified_and_more"),
    ]

    operations = []
