# Generated by Django 5.2.3 on 2025-06-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indieweb", "0006_merge_20250628_1513"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="me",
            field=models.CharField(max_length=512),
        ),
    ]
