# Generated by Django 5.2.13 on 2026-04-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indieweb", "0009_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
