# Generated by Django 5.2.13 on 2026-04-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indieweb", "0010_token_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="auth",
            name="code_challenge",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="auth",
            name="code_challenge_method",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
