# Generated by Django 5.2.13 on 2026-04-30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indieweb", "0011_auth_code_challenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="webmention",
            name="vouch_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="webmention",
            name="vouch_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
