# Generated by Django 6.0.4 on 2026-04-30 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indieweb", "0012_webmention_vouch"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebmentionSourceSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("raw_source_html", models.TextField()),
                ("final_source_url", models.URLField(max_length=500)),
                ("content_digest", models.CharField(max_length=64)),
                ("fetched_at", models.DateTimeField()),
                ("parsed_h_entry", models.JSONField(blank=True, default=dict)),
                ("nested_response_identities", models.JSONField(blank=True, default=list)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "webmention",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_snapshot",
                        to="indieweb.webmention",
                    ),
                ),
            ],
        ),
    ]
