# Generated by Django 6.0.4 on 2026-05-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indieweb", "0013_webmention_source_snapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebmentionNestedResponse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("identity", models.CharField(max_length=500)),
                ("response_url", models.URLField(blank=True, max_length=500)),
                ("author_name", models.CharField(blank=True, max_length=200)),
                ("author_url", models.URLField(blank=True)),
                ("author_photo", models.URLField(blank=True)),
                ("content", models.TextField(blank=True)),
                ("content_html", models.TextField(blank=True)),
                ("published", models.DateTimeField(blank=True, null=True)),
                (
                    "mention_type",
                    models.CharField(
                        choices=[
                            ("mention", "Mention"),
                            ("like", "Like"),
                            ("reply", "Reply"),
                            ("repost", "Repost"),
                        ],
                        default="mention",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("missing", "Missing"),
                            ("failed", "Failed"),
                            ("spam", "Spam"),
                        ],
                        default="verified",
                        max_length=20,
                    ),
                ),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("parsed_h_entry", models.JSONField(blank=True, default=dict)),
                ("content_digest", models.CharField(blank=True, max_length=64)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "webmention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nested_responses",
                        to="indieweb.webmention",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="webmentionnestedresponse",
            constraint=models.UniqueConstraint(
                fields=("webmention", "identity"),
                name="indieweb_nested_response_identity_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="webmentionnestedresponse",
            index=models.Index(fields=["webmention", "status"], name="indieweb_we_webment_460499_idx"),
        ),
        migrations.AddIndex(
            model_name="webmentionnestedresponse",
            index=models.Index(fields=["identity"], name="indieweb_we_identit_05b111_idx"),
        ),
    ]
