# Generated by Django 6.0.4 on 2026-05-02 05:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indieweb", "0014_webmention_nested_response"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebmentionOutboundTarget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source_url",
                    models.URLField(
                        db_index=True,
                        max_length=500,
                        validators=[django.core.validators.URLValidator(schemes=["http", "https"])],
                    ),
                ),
                (
                    "target_url",
                    models.URLField(
                        db_index=True,
                        max_length=500,
                        validators=[django.core.validators.URLValidator(schemes=["http", "https"])],
                    ),
                ),
                (
                    "endpoint_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        validators=[django.core.validators.URLValidator(schemes=["http", "https"])],
                    ),
                ),
                ("endpoint_discovered_at", models.DateTimeField(blank=True, null=True)),
                ("first_sent_at", models.DateTimeField(blank=True, null=True)),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                ("last_status_code", models.PositiveIntegerField(blank=True, null=True)),
                ("last_success", models.BooleanField(default=False)),
                ("last_error", models.TextField(blank=True)),
                (
                    "last_vouch_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        validators=[django.core.validators.URLValidator(schemes=["http", "https"])],
                    ),
                ),
                ("last_seen_in_source_at", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("source_url", "target_url"), name="indieweb_outbound_target_uniq")
                ],
            },
        ),
    ]
