# Generated by Django 6.0.4 on 2026-05-03 15:37

import django.core.validators
from django.db import migrations, models

import indieweb.models


class Migration(migrations.Migration):
    dependencies = [
        ("indieweb", "0015_webmention_outbound_target"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebSubSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "hub_url",
                    models.URLField(
                        max_length=500,
                        validators=[django.core.validators.URLValidator(schemes=["http", "https"])],
                    ),
                ),
                (
                    "topic_url",
                    models.URLField(
                        max_length=500,
                        validators=[django.core.validators.URLValidator(schemes=["http", "https"])],
                    ),
                ),
                (
                    "callback_token",
                    models.CharField(
                        db_index=True,
                        default=indieweb.models.generate_websub_callback_token,
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending_subscribe", "Pending subscribe"),
                            ("active", "Active"),
                            ("pending_unsubscribe", "Pending unsubscribe"),
                            ("unsubscribed", "Unsubscribed"),
                            ("denied", "Denied"),
                        ],
                        default="pending_subscribe",
                        max_length=32,
                    ),
                ),
                (
                    "pending_mode",
                    models.CharField(
                        blank=True,
                        choices=[("subscribe", "Subscribe"), ("unsubscribe", "Unsubscribe")],
                        max_length=16,
                    ),
                ),
                ("requested_lease_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("confirmed_lease_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("secret", models.CharField(blank=True, max_length=200)),
                ("pending_secret", models.CharField(blank=True, max_length=200)),
                ("pending_secret_set", models.BooleanField(default=False)),
                ("last_challenge", models.CharField(blank=True, max_length=200)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("last_request_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_request_mode",
                    models.CharField(
                        blank=True,
                        choices=[("subscribe", "Subscribe"), ("unsubscribe", "Unsubscribe")],
                        max_length=16,
                    ),
                ),
                ("last_request_status_code", models.PositiveIntegerField(blank=True, null=True)),
                ("last_request_error", models.TextField(blank=True)),
                ("last_delivery_at", models.DateTimeField(blank=True, null=True)),
                ("last_delivery_content_type", models.CharField(blank=True, max_length=200)),
                ("last_delivery_size", models.PositiveIntegerField(blank=True, null=True)),
                ("last_delivery_digest", models.CharField(blank=True, max_length=64)),
                ("last_delivery_signature_algorithm", models.CharField(blank=True, max_length=32)),
                ("last_delivery_status_code", models.PositiveIntegerField(blank=True, null=True)),
                ("last_delivery_error", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["topic_url", "state"], name="indieweb_we_topic_u_2b3ef6_idx"),
                    models.Index(fields=["lease_expires_at"], name="indieweb_we_lease_e_86c6d4_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("hub_url", "topic_url"),
                        name="indieweb_websub_hub_topic_uniq",
                    )
                ],
            },
        ),
    ]
