# Generated by Django 6.0.4 on 2026-05-03 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indieweb", "0016_websubsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="websubsubscription",
            name="last_denial_reason",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="websubsubscription",
            name="last_denied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="websubsubscription",
            name="last_denied_mode",
            field=models.CharField(
                blank=True, choices=[("subscribe", "Subscribe"), ("unsubscribe", "Unsubscribe")], max_length=16
            ),
        ),
        migrations.CreateModel(
            name="WebSubDeliveryAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("received_at", models.DateTimeField(db_index=True)),
                ("content_type", models.CharField(blank=True, max_length=200)),
                ("size", models.PositiveIntegerField(blank=True, null=True)),
                ("digest", models.CharField(blank=True, max_length=64)),
                ("signature_algorithm", models.CharField(blank=True, max_length=32)),
                ("status_code", models.PositiveIntegerField()),
                ("error", models.CharField(blank=True, max_length=500)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_attempts",
                        to="indieweb.websubsubscription",
                    ),
                ),
            ],
            options={
                "ordering": ("-received_at", "-pk"),
                "indexes": [
                    models.Index(fields=["subscription", "received_at"], name="indieweb_we_subscri_d28c9d_idx"),
                    models.Index(fields=["status_code", "received_at"], name="indieweb_we_status__2a11f1_idx"),
                ],
            },
        ),
    ]
