# Generated by Django 6.0.4 on 2026-05-06 16:34

from django.db import migrations, models
from django.db.models import Count
from django.utils.crypto import get_random_string


def rotate_duplicate_keys(apps, schema_editor):
    """Keep one row per existing key and rotate any accidental duplicates before adding uniqueness."""
    for model_name in ("Auth", "Token"):
        model = apps.get_model("indieweb", model_name)
        existing_keys = set(model.objects.values_list("key", flat=True))
        duplicate_keys = (
            model.objects.values("key")
            .annotate(key_count=Count("id"))
            .filter(key_count__gt=1)
            .values_list("key", flat=True)
        )
        for key in duplicate_keys:
            duplicate_rows = model.objects.filter(key=key).order_by("id").values_list("id", flat=True)
            for row_id in list(duplicate_rows)[1:]:
                new_key = get_random_string(length=32)
                while new_key in existing_keys:
                    new_key = get_random_string(length=32)
                model.objects.filter(id=row_id).update(key=new_key)
                existing_keys.add(new_key)


class Migration(migrations.Migration):
    dependencies = [
        ("indieweb", "0017_websubsubscription_last_denial_reason_and_more"),
    ]

    operations = [
        migrations.RunPython(rotate_duplicate_keys, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="auth",
            name="key",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="token",
            name="key",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
