# Generated by Django 6.0.4 on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indieweb", "0018_alter_auth_key_alter_token_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="webmentionoutboundtarget",
            name="consecutive_failures",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="webmentionoutboundtarget",
            name="last_attempted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
