# Generated by Codex on 2026-05-07

from __future__ import annotations

import base64
import hashlib
import hmac
import logging

from cryptography.fernet import Fernet, InvalidToken
from django.conf import settings
from django.db import migrations, models

WEBSUB_SECRET_ENCRYPTED_PREFIX = "fernet$"
WEBSUB_SECRET_KEY_SALT = b"django-indieweb-websub-secret-v1"
logger = logging.getLogger(__name__)


def _websub_secret_fernet() -> Fernet:
    key_material = hmac.new(
        str(settings.SECRET_KEY).encode("utf-8"),
        WEBSUB_SECRET_KEY_SALT,
        hashlib.sha256,
    ).digest()
    return Fernet(base64.urlsafe_b64encode(key_material))


def _encrypt_secret(value: str) -> str:
    if not value or value.startswith(WEBSUB_SECRET_ENCRYPTED_PREFIX):
        return value
    token = _websub_secret_fernet().encrypt(value.encode("utf-8")).decode("ascii")
    return f"{WEBSUB_SECRET_ENCRYPTED_PREFIX}{token}"


def _decrypt_secret(value: str) -> str:
    if not value or not value.startswith(WEBSUB_SECRET_ENCRYPTED_PREFIX):
        return value
    token = value.removeprefix(WEBSUB_SECRET_ENCRYPTED_PREFIX)
    try:
        return _websub_secret_fernet().decrypt(token.encode("ascii")).decode("utf-8")
    except (InvalidToken, UnicodeDecodeError):
        logger.warning(
            "Could not decrypt a WebSub secret during reverse migration; leaving encrypted value in place",
            exc_info=True,
        )
        return value


def encrypt_websub_secrets(apps, schema_editor) -> None:  # type: ignore[no-untyped-def]
    WebSubSubscription = apps.get_model("indieweb", "WebSubSubscription")
    for subscription in WebSubSubscription.objects.all().iterator():
        updated_fields = []
        encrypted_secret = _encrypt_secret(subscription.secret)
        if encrypted_secret != subscription.secret:
            subscription.secret = encrypted_secret
            updated_fields.append("secret")
        encrypted_pending_secret = _encrypt_secret(subscription.pending_secret)
        if encrypted_pending_secret != subscription.pending_secret:
            subscription.pending_secret = encrypted_pending_secret
            updated_fields.append("pending_secret")
        if updated_fields:
            subscription.save(update_fields=updated_fields)


def decrypt_websub_secrets(apps, schema_editor) -> None:  # type: ignore[no-untyped-def]
    WebSubSubscription = apps.get_model("indieweb", "WebSubSubscription")
    for subscription in WebSubSubscription.objects.all().iterator():
        updated_fields = []
        decrypted_secret = _decrypt_secret(subscription.secret)
        if decrypted_secret != subscription.secret:
            subscription.secret = decrypted_secret
            updated_fields.append("secret")
        decrypted_pending_secret = _decrypt_secret(subscription.pending_secret)
        if decrypted_pending_secret != subscription.pending_secret:
            subscription.pending_secret = decrypted_pending_secret
            updated_fields.append("pending_secret")
        if updated_fields:
            subscription.save(update_fields=updated_fields)


class Migration(migrations.Migration):
    dependencies = [
        ("indieweb", "0020_hash_token_keys_and_webmention_status_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="websubsubscription",
            name="pending_secret",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="websubsubscription",
            name="secret",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="websubsubscription",
            name="last_accepted_delivery_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="websubsubscription",
            name="last_accepted_delivery_digest",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunPython(encrypt_websub_secrets, decrypt_websub_secrets),
    ]
