# Generated by Django 6.0.4 on 2026-05-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indieweb", "0023_hash_auth_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="webmention",
            name="last_received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
