# Generated by Django 6.0.4 on 2026-05-09 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indieweb", "0026_drop_recent_accepted_delivery_digests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webmention",
            name="author_photo",
            field=models.URLField(
                blank=True,
                validators=[django.core.validators.URLValidator(schemes=["http", "https"])],
            ),
        ),
        migrations.AlterField(
            model_name="webmention",
            name="author_url",
            field=models.URLField(
                blank=True,
                validators=[django.core.validators.URLValidator(schemes=["http", "https"])],
            ),
        ),
    ]
