# Generated by Django 6.0.4 on 2026-05-10 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indieweb", "0027_alter_webmention_author_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webmentionnestedresponse",
            name="author_photo",
            field=models.URLField(
                blank=True,
                validators=[django.core.validators.URLValidator(schemes=["http", "https"])],
            ),
        ),
        migrations.AlterField(
            model_name="webmentionnestedresponse",
            name="author_url",
            field=models.URLField(
                blank=True,
                validators=[django.core.validators.URLValidator(schemes=["http", "https"])],
            ),
        ),
        migrations.AlterField(
            model_name="webmentionnestedresponse",
            name="identity",
            field=models.CharField(
                max_length=500,
                validators=[django.core.validators.URLValidator(schemes=["http", "https"])],
            ),
        ),
        migrations.AlterField(
            model_name="webmentionnestedresponse",
            name="response_url",
            field=models.URLField(
                blank=True,
                max_length=500,
                validators=[django.core.validators.URLValidator(schemes=["http", "https"])],
            ),
        ),
    ]
